### ISSUE TITLE
[BUG] Crash when scanning clustist portal

### ISSUE THREAD

**Issue by KELETU66666** [Wong-Innovations/TC4Research#15]
---- Minecraft Crash Report ----
// There are four lights!

Time: 2/22/24 9:56 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at thaumcraft.common.items.tools.ItemThaumometer.onUsingTick(ItemThaumometer.java:578)
	at net.minecraft.entity.EntityLivingBase.updateActiveHand(EntityLivingBase.java:2952)
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2316)
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:271)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2171)
	at net.minecraft.world.World.updateEntity(World.java:2130)
	at net.minecraft.world.World.updateEntities(World.java:1931)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1974)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1188)
	at net.minecraft.client.Minecraft.run(Minecraft.java:442)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:87)
	at GradleStart.main(GradleStart.java:19)

(MixinBooter) Mixins in Stacktrace:
	thaumcraft/common/items/tools/ItemThaumometer:
		com.wonginnovations.oldresearch.core.mixin.ItemThaumometerMixin (mixins.oldresearch.json) [oldresearch-1.0.0-dev.jar]
	net/minecraft/item/Item:
		com.cleanroommc.groovyscript.core.mixin.ItemMixin (mixin.groovyscript.json) [unknown-location]
	net/minecraft/entity/Entity:
		com.cleanroommc.groovyscript.core.mixin.EntityAccessor (mixin.groovyscript.json) [unknown-location]
	net/minecraft/client/Minecraft:
		com.cleanroommc.groovyscript.core.mixin.DefaultResourcePackAccessor (mixin.groovyscript.json) [unknown-location]
	net/minecraft/entity/Entity:
		com.cleanroommc.groovyscript.core.mixin.EntityAccessor (mixin.groovyscript.json) [unknown-location]
	net/minecraft/entity/Entity:
		com.cleanroommc.groovyscript.core.mixin.EntityAccessor (mixin.groovyscript.json) [unknown-location]

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thaumcraft.common.items.tools.ItemThaumometer.onUsingTick(ItemThaumometer.java:578)
	at net.minecraft.entity.EntityLivingBase.updateActiveHand(EntityLivingBase.java:2952)
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2316)
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:271)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2171)
	at net.minecraft.world.World.updateEntity(World.java:2130)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 268
	Entity Name: SumTingWong886
	Entity's Exact location: -73.03, 70.00, 281.40
	Entity's Block location: World: (-74,70,281), Chunk: (at 6,4,9 in -5,17; contains blocks -80,0,272 to -65,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1931)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['SumTingWong886'/268, l='MpServer', x=-73.03, y=70.00, z=281.40]]
	Chunk stats: MultiplayerChunkCache: 575, 575
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-180,64,212), Chunk: (at 12,4,4 in -12,13; contains blocks -192,0,208 to -177,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 41034 game time, 51826 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 81 total; [EntityRabbit['Rabbit'/256, l='MpServer', x=-14.50, y=68.00, z=307.50], EntityRabbit['Rabbit'/257, l='MpServer', x=-9.61, y=68.00, z=299.72], EntityRabbit['Rabbit'/258, l='MpServer', x=-2.50, y=69.00, z=329.50], EntityRabbit['Rabbit'/259, l='MpServer', x=-3.60, y=69.00, z=333.40], EntityItem['item.item.rottenFlesh'/772, l='MpServer', x=-139.87, y=64.00, z=271.90], EntityRabbit['Rabbit'/260, l='MpServer', x=1.28, y=69.00, z=331.98], EntityCreeper['Creeper'/3594, l='MpServer', x=-70.58, y=17.00, z=234.82], EntityBat['Bat'/4877, l='MpServer', x=-65.83, y=24.55, z=231.06], EntityCreeper['Creeper'/2327, l='MpServer', x=-69.50, y=35.00, z=227.50], EntityItem['item.item.arrow'/791, l='MpServer', x=-55.72, y=71.00, z=251.39], EntityPlayerSP['SumTingWong886'/268, l='MpServer', x=-73.03, y=70.00, z=281.40], EntityCreeper['Creeper'/5914, l='MpServer', x=-31.50, y=18.00, z=245.50], EntityBat['Bat'/4123, l='MpServer', x=-115.26, y=34.06, z=246.92], EntityCreeper['Creeper'/5915, l='MpServer', x=-28.50, y=18.00, z=238.50], EntityCreeper['Creeper'/5916, l='MpServer', x=-30.50, y=18.00, z=237.50], EntitySpider['Spider'/6174, l='MpServer', x=-43.50, y=15.00, z=222.50], EntityZombie['Zombie'/4132, l='MpServer', x=-146.50, y=41.00, z=327.50], EntitySkeleton['Skeleton'/6181, l='MpServer', x=-57.50, y=21.00, z=241.50], EntityCreeper['Creeper'/3111, l='MpServer', x=-110.50, y=25.00, z=337.50], EntitySpider['Spider'/6183, l='MpServer', x=-59.50, y=21.00, z=241.50], EntityBat['Bat'/5943, l='MpServer', x=-121.25, y=39.48, z=258.05], EntitySquid['Squid'/2872, l='MpServer', x=-90.02, y=51.46, z=338.05], EntityCreeper['Creeper'/4671, l='MpServer', x=-154.50, y=36.00, z=288.50], EntityCreeper['Creeper'/5445, l='MpServer', x=-24.50, y=13.00, z=323.50], EntityCreeper['Creeper'/5198, l='MpServer', x=-115.50, y=22.00, z=338.50], EntityCreeper['Creeper'/5199, l='MpServer', x=-118.50, y=22.00, z=338.50], EntitySquid['Squid'/2896, l='MpServer', x=-79.53, y=60.52, z=333.73], EntitySquid['Squid'/2897, l='MpServer', x=-78.29, y=60.24, z=331.49], EntityCreeper['Creeper'/5206, l='MpServer', x=-124.50, y=36.00, z=216.50], EntityCreeper['Creeper'/5207, l='MpServer', x=-123.50, y=36.00, z=216.50], EntitySkeleton['Skeleton'/4443, l='MpServer', x=-58.50, y=21.00, z=247.50], EntityBat['Bat'/6239, l='MpServer', x=-127.15, y=37.00, z=349.79], EntityBat['Bat'/1377, l='MpServer', x=-23.72, y=56.98, z=245.24], EntityCreeper['Creeper'/5985, l='MpServer', x=-33.50, y=15.31, z=313.81], EntityWitch['Witch'/5223, l='MpServer', x=-83.50, y=25.00, z=255.50], EntityCreeper['Creeper'/5225, l='MpServer', x=-88.42, y=35.00, z=248.19], EntitySkeleton['Skeleton'/5226, l='MpServer', x=-76.50, y=35.00, z=243.50], EntitySkeleton['Skeleton'/5739, l='MpServer', x=-34.57, y=31.00, z=340.17], EntitySkeleton['Skeleton'/2682, l='MpServer', x=-127.29, y=35.00, z=253.48], EntityCreeper['Creeper'/6018, l='MpServer', x=-29.50, y=68.00, z=223.50], EntityZombie['Zombie'/3206, l='MpServer', x=-141.50, y=43.00, z=269.50], EntityCreeper['Creeper'/3207, l='MpServer', x=-147.44, y=46.00, z=265.79], EntityBat['Bat'/5513, l='MpServer', x=-123.05, y=35.17, z=217.95], EntityCreeper['Creeper'/147, l='MpServer', x=-144.53, y=36.00, z=247.23], EntitySkeleton['Skeleton'/4502, l='MpServer', x=-98.50, y=20.00, z=256.50], EntityCreeper['Creeper'/4769, l='MpServer', x=-155.50, y=14.00, z=347.50], EntityCultistKnight['Crimson Knight'/6053, l='MpServer', x=-68.77, y=70.00, z=284.16], EntitySkeleton['Skeleton'/3495, l='MpServer', x=-36.50, y=60.00, z=241.50], EntityBat['Bat'/174, l='MpServer', x=-125.75, y=38.10, z=252.44], EntityRabbit['Rabbit'/176, l='MpServer', x=-105.54, y=70.20, z=272.93], EntityRabbit['Rabbit'/185, l='MpServer', x=-103.27, y=67.00, z=214.91], EntityHusk['Husk'/187, l='MpServer', x=-121.50, y=64.00, z=239.28], EntityHusk['Husk'/189, l='MpServer', x=-114.20, y=67.00, z=250.71], EntityRabbit['Rabbit'/190, l='MpServer', x=-108.02, y=69.00, z=271.48], EntityEnderman['Enderman'/5824, l='MpServer', x=-147.50, y=42.00, z=299.50], EntitySpider['Spider'/5826, l='MpServer', x=-52.50, y=24.00, z=243.50], EntityRabbit['Rabbit'/197, l='MpServer', x=-88.88, y=70.00, z=268.61], EntityRabbit['Rabbit'/205, l='MpServer', x=-79.50, y=70.00, z=267.50], EntityRabbit['Rabbit'/206, l='MpServer', x=-78.60, y=70.00, z=268.40], EntityCultistPortalLesser['Lesser Crimson Portal'/208, l='MpServer', x=-69.50, y=70.00, z=283.50], EntityZombie['Zombie'/3793, l='MpServer', x=-152.81, y=15.00, z=255.51], EntityBat['Bat'/5075, l='MpServer', x=-148.24, y=15.08, z=249.64], EntityCreeper['Creeper'/6100, l='MpServer', x=-94.50, y=19.00, z=260.50], EntityBat['Bat'/5077, l='MpServer', x=-139.11, y=11.96, z=212.94], EntityRabbit['Rabbit'/231, l='MpServer', x=-49.97, y=78.00, z=229.51], EntityCreeper['Creeper'/5607, l='MpServer', x=-74.53, y=16.00, z=239.10], EntityRabbit['Rabbit'/232, l='MpServer', x=-34.62, y=83.00, z=230.71], EntitySkeleton['Skeleton'/5608, l='MpServer', x=-74.50, y=16.00, z=239.74], EntityRabbit['Rabbit'/233, l='MpServer', x=-30.71, y=69.00, z=245.26], EntityBat['Bat'/5865, l='MpServer', x=-79.91, y=15.60, z=239.90], EntityRabbit['Rabbit'/234, l='MpServer', x=-29.42, y=72.00, z=237.20], EntityBat['Bat'/5866, l='MpServer', x=-72.43, y=18.22, z=237.18], EntityRabbit['Rabbit'/235, l='MpServer', x=-34.06, y=70.00, z=251.41], EntityRabbit['Rabbit'/239, l='MpServer', x=-27.79, y=72.00, z=210.08], EntityRabbit['Rabbit'/240, l='MpServer', x=-24.56, y=72.00, z=210.30], EntityBat['Bat'/5361, l='MpServer', x=-88.48, y=20.63, z=253.46], EntityRabbit['Rabbit'/244, l='MpServer', x=-24.22, y=68.00, z=247.21], EntitySkeleton['Skeleton'/2549, l='MpServer', x=-112.50, y=33.00, z=246.50], EntityRabbit['Rabbit'/245, l='MpServer', x=-26.25, y=68.00, z=247.38], EntityRabbit['Rabbit'/246, l='MpServer', x=-26.79, y=68.00, z=247.42], EntityRabbit['Rabbit'/247, l='MpServer', x=-16.87, y=68.00, z=314.68]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:456)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2889)
	at net.minecraft.client.Minecraft.run(Minecraft.java:463)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:87)
	at GradleStart.main(GradleStart.java:19)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_402, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.
	Memory: 1186353008 bytes (1131 MB) / 2596274176 bytes (2476 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -Xms1G -Xmx6G
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version      | Source                                  | Signature |
	|:------ |:--------------- |:------------ |:--------------------------------------- |:--------- |
	| LCHIJA | minecraft       | 1.12.2       | minecraft.jar                           | None      |
	| LCHIJA | mcp             | 9.42         | minecraft.jar                           | None      |
	| LCHIJA | mixinbooter     | 8.8          | minecraft.jar                           | None      |
	| LCHIJA | FML             | 8.0.99.99    | recompiled_minecraft-1.12.2.jar         | None      |
	| LCHIJA | forge           | 14.23.5.2847 | recompiled_minecraft-1.12.2.jar         | None      |
	| LCHIJA | placeholdername | 1.0.0        | groovyscript-687577-5120928-deobf.jar   | None      |
	| LCHIJA | baubles         | 1.5.2        | baubles-227083-2518667-deobf.jar        | None      |
	| LCHIJA | thaumcraft      | 6.1.BETA26   | thaumcraft-223628-2629023-deobf.jar     | None      |
	| LCHIJA | oldresearch     | 1.0.0        | oldresearch-1.0.0-dev.jar               | None      |
	| LCHIJA | jei             | 4.16.1.302   | jei_1.12.2-4.16.1.302.jar               | None      |
	| LCHIJA | theoneprobe     | 1.4.28       | top-245211-2667280-deobf.jar            | None      |
	| LCHIJA | codechickenlib  | 3.2.3.358    | codechickenlib-242818-2779848-deobf.jar | None      |
	| LCHIJA | groovyscript    | 0.8.0        | groovyscript-687577-5120928-deobf.jar   | None      |

	Loaded coremods (and transformers): 
GroovyScript-Core (groovyscript-687577-5120928-deobf.jar)
  
MixinBooter (mixinbooter-8.8.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.9664' Renderer: 'Intel(R) UHD Graphics'
	Launched Version: FML_DEV
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics GL version 4.6.0 - Build 27.20.100.9664, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

**Comment by Wong-Innovations** [comment]
great find, thank you for the well documented bug! once I resolve the build errors I'll give this one some attention. I hope you'll continue to assist me in playtesting the project.

**Comment by Wong-Innovations** [comment]
fixed in commit: https://github.com/Wong-Innovations/TC4Research/commit/cc4497ee386c79a4c8823ec14a4f3344233d1a07
