### ISSUE TITLE
[BUG] Complex Research can't works correctly

### ISSUE THREAD

**Issue by KELETU66666** [Wong-Innovations/TC4Research#17]
![image](https://github.com/Wong-Innovations/TC4Research/assets/92129388/18bf3ec1-339f-45e5-ae94-c332ba838ff5)

**Comment by KELETU66666** [comment]
all the complex research all has this bug, no matter in dev env or client env, pls fix it, thanks in advanced :)

**Comment by KELETU66666** [comment]
after cause this bug, error occurred in all the research notes.

**Comment by Wong-Innovations** [comment]
Hi Keletu, the way research complexity is supposed to work by default is that they just get more complex as you complete more and more notes. Obviously that is not what is happening here so I'll take a look.

good find.

**Comment by Wong-Innovations** [comment]
unable to reproduce in the latest 1.0.1 jar. please test with latest release.
