### ISSUE TITLE
[BUG] Infinity Reserach Points

### ISSUE THREAD

**Issue by KELETU66666** [Wong-Innovations/TC4Research#18]
Uploading QQ2024222-183631.mp4…

**Comment by KELETU66666** [comment]
Uploading QQ2024222-183631.mp4…

**Comment by KELETU66666** [comment]
https://github.com/Wong-Innovations/TC4Research/assets/92129388/644db6b7-a9e5-43b2-9bf4-7baf04a5de48

**Comment by Wong-Innovations** [comment]
wow that's a weird one....
Thanks I'll look into it.

**Comment by Wong-Innovations** [comment]
unable to reproduce in the latest built jar. please test using the latest jar from CF or GitHub. (1.0.1 as of today)
