### ISSUE TITLE
[BUG] OpenGL Error

### ISSUE THREAD

**Issue by KELETU66666** [Wong-Innovations/TC4Research#19]
![image](https://github.com/Wong-Innovations/TC4Research/assets/92129388/fa057978-4e3a-4c76-b2a5-86d51ad59e88)

from latest.log

**Comment by Wong-Innovations** [comment]
I have noticed this when scanning certain things with the thaumometer. I don't yet know what is causing it. Thank you for creating this issue.

**Comment by Wong-Innovations** [comment]
fixed in commit: https://github.com/Wong-Innovations/TC4Research/commit/91ee8b35071bff2ab5141990a784810dddf79e30
changes will be live in 1.0.1
