### ISSUE TITLE
Bugs I've found.

### ISSUE THREAD

**Issue by xxXCuriositykilledthecatXxx** [Wong-Innovations/TC4Research#25]
Chests and certain other interactable blocks give infinite research, while others, like beds, can't be scanned. Dropped items can't be scanned. Liquids like lava and water seem unscanable. However, I apparently managed to scan water, which I don't remember and can't replicate. Finally, for some reason, this bauxite ore is displaying an aspect that doesn't exist, which goes away when I remove this mod. I forgot to show it, but I also can't scan animals.
[bugs.webm](https://github.com/Wong-Innovations/TC4Research/assets/89814183/da13f59a-6d64-4b68-b58b-2a499487e487)

**Comment by Wong-Innovations** [comment]
@xxXCuriositykilledthecatXxx thank you for your interest in my mod. When I open a fresh creative world I don’t see any of these issues. Mind helping me do a bit more troubleshooting by answering some questions?

1. Are you using the latest version of the mod? (1.0.1 at time of posting this)
2. How did you obtain the mod? (Curseforge or github release)
3. Do you see these errors when launching with just this mod and thaumcraft (and baubles since that’s a thaum dependency) or do you have other mods in your instance that might be conflicting.

**Comment by xxXCuriositykilledthecatXxx** [comment]
I am using the latest version, first obtained from Curseforge later from Github. I just tried it without anything else and it simply broke, it acted like it wasn't installed. I tried reinstalling, switching to a brand new instance as I was using a testing instance, and it just stopped working. Also all the aspect textures are now broken.
![asdfgasdfgsdfsdfsdfasdfsdfg](https://github.com/Wong-Innovations/TC4Research/assets/89814183/bfa06798-269e-439d-a0e4-b111d624ac89)

**Comment by Wong-Innovations** [comment]
I apologize in advanced, as I'll probably have to keep asking follow up questions since several people I've talked with are actively using the mod without these issues (myself included). Screenshots are helpful, thank you for providing them.

The top bar of your minecraft window looks odd. Are you using forge mod loader? What operating system and modded client?

**Comment by xxXCuriositykilledthecatXxx** [comment]
I'm using forge mod loader version 14.23.5.2860, however on a different instance I made to test this it was on 14.23.5.2859. SO let me test if this is a forge version issue. I'm also on linux. 
I've booted up my normal instance where I was first messing with the mod, and it's working perfectly besides the issues I originally listed.
![asdfgsdfgdgsdfasdfsdfsdgsdgh](https://github.com/Wong-Innovations/TC4Research/assets/89814183/0bf781d9-d05a-4327-a3b7-b37e398c3515)

**Comment by xxXCuriositykilledthecatXxx** [comment]
I changed forge versions, and the issues persist.

**Comment by Wong-Innovations** [comment]
hang on a second. Why does your chest have Spatio? what mod adds that aspect? whatever addons you are using might be causing the issues.

**Comment by xxXCuriositykilledthecatXxx** [comment]
That's planar artifice, and I'm currently trying mod combinations to see what is making this mod work for me in my main instance. So far I've checked thaumic speedup.

**Comment by xxXCuriositykilledthecatXxx** [comment]
Alright I found it. For some reason the mod doesn't work for me without mixin booster. I have the 8.9 version installed.

**Comment by KELETU66666** [comment]
i thought this mod require mixin booter mod

**Comment by xxXCuriositykilledthecatXxx** [comment]
Also, all the issues I started this thread with still exist, even after updating mixin booster. However, confusingly, I managed to scan an ignis crystal, yet I can't replicate this on other dropped items.

**Comment by xxXCuriositykilledthecatXxx** [comment]
I just managed to figure out that I can scan dropped items; I just need to scan them without a block behind them. However, different vis crystals seem to all be considered one scan. None of them have the particles that show that you can scan them after I scanned an ignis crystal.

**Comment by Wong-Innovations** [comment]
> i thought this mod require mixin booter mod

It does require mixin booter, I've been using 8.8 but 8.9 should work fine.

**Comment by xxXCuriositykilledthecatXxx** [comment]
> It does require mixin booter, I've been using 8.8 but 8.9 should work fine.

Please put that information on the Curseforge page, and the github readme.

**Comment by xxXCuriositykilledthecatXxx** [comment]
I just tested it and the mod works perfectly with mixin booster 8.8, it seems all my issues are from using a newer version.

**Comment by xxXCuriositykilledthecatXxx** [comment]
> I just tested it and the mod works perfectly with mixin booster 8.8, it seems all my issues are from using a newer version.

I take that back. The liquid scanning issue and the item scanning issue are still present.

**Comment by xxXCuriositykilledthecatXxx** [comment]
The newest update fixed all of this issues.
