### ISSUE TITLE
Research Duplication

### ISSUE THREAD

**Issue by Dawnwalker666** [Wong-Innovations/TC4Research#30]
As shown in the picture. It is displayed as "tc.research.copy". Note that it is displayed as this regardless of language.
![QQ截图20240224184808](https://github.com/Wong-Innovations/TC4Research/assets/49862610/bbd3be7f-89bb-457b-8b28-6fb7e65aca6a)

Also, when the lower aspect compositing bar fills up, the top yellow star icon will be replaced with a primordial pearl. Of course I know that's what the thaumcraft looks like, but a fix would be nice.
![QQ截图20240224185259](https://github.com/Wong-Innovations/TC4Research/assets/49862610/94f1e5fa-9204-4eff-84c8-3be018a68dd9)

I guess this text is showing how much aspect I need to duplicate?

**Comment by Dawnwalker666** [comment]
I'm not even sure the feature works. Or maybe it's just a text display error. I got the source's aspect to over 100 points each (since there's no command that lets me get ASPECT quickly).  But ... still can't research duplication.

**Comment by Wong-Innovations** [comment]
@Dawnwalker666 Thank you for pointing this out, I'll take a look at the research table's code and try to fix this for the next release.

**Comment by Wong-Innovations** [comment]
Fixed in commit: https://github.com/Wong-Innovations/TC4Research/commit/c4300cd0a00612bbd9bb67cf4b9b6afec394ae61
this will be included in 1.1.1 which I'm about to push.
