### ISSUE TITLE
[BUG] Server crash with this mod

### ISSUE THREAD

**Issue by KELETU66666** [Wong-Innovations/TC4Research#31]
---- Minecraft Crash Report ----// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.// There are four lights!Time: 2024-02-25 00:21:18 CSTDescription: Exception in server tick loopjava.lang.NoClassDefFoundError: net/minecraft/client/gui/toasts/IToast    at com.wonginnovations.oldresearch.common.items.ModItems.<clinit>(ModItems.java:14)    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1017_ModItems_registerItems_Register.invoke(.dynamic)    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:146)    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:336)    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:169)    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1954)    at java.lang.Thread.run(Thread.java:750)Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.toasts.IToast    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)    ... 12 moreCaused by: java.lang.NullPointerExceptionNo Mixin Metadata is found in the Stacktrace.A detailed walkthrough of the error, its code path and all known details is as follows:----------------------------------------------------------------------------------------- System Details --  Minecraft Version: 1.12.2  Operating System: Windows 11 (amd64) version 10.0  Java Version: 1.8.0_382, Alibaba  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Alibaba  Memory: 3081029016 bytes (2938 MB) / 4294967296 bytes (4096 MB) up to 16106127360 bytes (15360 MB)  JVM Flags: 7 total; -Xmx15G -Xms4G -XX:+UseG1GC -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=10 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=11  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0  CraftBukkit Information: Running:                               Failed to handle CraftCrashReport:                           java.lang.NullPointerException                           at org.bukkit.Bukkit.getName(Bukkit.java:92)                           at org.bukkit.craftbukkit.v1_12_R1.CraftCrashReport.call(CraftCrashReport.java:20)                           at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96)                           at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:120)                           at net.minecraft.crash.CrashReport.<init>(CrashReport.java:41)                           at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:2022)                           at java.lang.Thread.run(Thread.java:750)  FML: MCP 9.42 LoliASM 5.19 VintageFix 0.4.0 Powered by Forge 14.23.5.2860 243 mods loaded, 243 mods active

**Comment by Wong-Innovations** [comment]
fixed in commit: https://github.com/Wong-Innovations/TC4Research/commit/afdaf826e07f6e96772a3cd0e240984b4b13e3cf
will be in next release
