### ISSUE TITLE
[Feedback] inventory scan is not available under certain conditions

### ISSUE THREAD

**Issue by Dawnwalker666** [Wong-Innovations/TC4Research#35]
oldresearch-1.1.1.jar

It may not be accurate to say that, inventory scanning is only available when you open the research table. I don't know if this is a bug or a feature ;) .
But would prefer to be able to open the inventory and just scan it. Otherwise, going through boxes when there are too many items can be a pain in the ass, as it would require having a research table with you at all times.
By the way request to add a command to get aspect quickly. Just like old times.

**Comment by Wong-Innovations** [comment]
Hi @Dawnwalker666 Can you please see if this is still an issue with version 1.1.2 jar? I've been unable to reproduce it, if you do see the issue still on the latest version can you provide some more information? Are you playing single player, on a server, etc...

**Comment by Dawnwalker666** [comment]
@Wong-Innovations Looking at your reply, this seems to be a bug rather than a feature. Sorry, I'll add more details then.
This time I'm using 1.1.2. the latest version.

jdk1.8.0_281
minecraft 1.12.2
forge 1.12.2-14.23.5.2854

**modlist:**
ThaumicWaila-1.12.2-0.0.2.jar
jei_1.12.2-4.15.0.291.jar
Hwyla-1.8.26-B41_1.12.2.jar
AppleSkin-mc1.12-1.0.9.jar
journeymap-1.12.2-5.5.5b7.jar
VanillaFix-1.0.10-150.jar
Baubles-1.12-1.5.2.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
JustEnoughCharacters-1.12.0-3.4.7.jar
**oldresearch-1.1.2.jar**
Patchouli-1.0-23.6.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
***
![动画](https://github.com/Wong-Innovations/TC4Research/assets/49862610/4564fa5e-0ee9-43ce-ba0f-bef5aba734c5)
As shown in this gif. Inventory scanning is only available when you open the research table. The first and second items did not scan. When using the Thaumometer it only scans when the research table is open and it scans successfully.
Using a single-player archive. Superflat and Redstone Ready.

**Comment by Dawnwalker666** [comment]
As well, I retested it with only the necessary mods and still got this result. So it's safe to assume it's not a mod conflict.

**Comment by Wong-Innovations** [comment]
@Dawnwalker666 do you not have !mixinbooter installed?.... I don't see it in your mod list.

**Comment by Wong-Innovations** [comment]
the code disables inventory scanning in creative tab because that's what the 1.7.10 mod did. I'll add a config value to enable scanning in the creative menu which is off by default.
