### ISSUE TITLE
[Bug] Player "lose" aspects after re-login to server

### ISSUE THREAD

**Issue by RisingInIris2017** [Wong-Innovations/TC4Research#36]
## Overview
I see this issue only on an dedicated server, and have not see this happen on singleplayer game.
It may not reproduce every time when you re-login after logging out from server.
In other words, the problem may not be reproduced stably.

## How to reproduce
1. Unlock some researches by scanning or researching.
2. Log out from the dedicated server, then re-login.
3. If this issue is successfully reproduced, you will see your Aspects are lost, their icons become dim, just like it was not unlocked.
4. Do some scanning or obtain some Aspects. If you have unlocked a research corresponding to this scan or Aspects before this issue happens, it will be unlocked again.

If any other information is needed, feel free to tell me in reply. I will provide it as soon as possible.
Thanks in advance.

**Comment by Wong-Innovations** [comment]
I was able to reproduce this error, thank you for creating this detailed issue. I'll be working on fixing this for the 1.1.3 release. Hope you enjoy the mod!

**Comment by Wong-Innovations** [comment]
should be fixed with this commit: https://github.com/Wong-Innovations/TC4Research/commit/268a3c549303b1bdf8f94d78e1a6aa1f917213ba
