### ISSUE TITLE
Misc Suggestions

### ISSUE THREAD

**Issue by IcarussOne** [Wong-Innovations/TC4Research#40]
These aren't part of the research system, but I think they might fit the mod's overall scope.

**Warp:**
Warp had an overlay effect when warp events happen in TC4 but this does not happen in TC6. You actually can still see the overlay effect while the Deadly Gaze effect is active so restoring this shouldn't be too difficult.

**Champion Mobs:**
Another missing feature from TC6, champion mobs exist in the mod's code but do not spawn naturally. I think this would be a great feature to obtain the newly enhanced curios from.

**Runic Shielding HUD:**
While runic shielding is active in TC4, an animated overlay effect would display on your health. This was since replaced with absorption hearts as of TC5, a mod called [Thaumcraft 6 Enhanced](https://www.curseforge.com/minecraft/mc-mods/thaumcraft-6-enhanced) attempts to restore this but it is incompatible with Thaumic Augmentation and hasn't been updated for a long time.

**Thaumonomicon Font:**
The Thaumonomicon used the unicode font in earlier Thaumcraft versions. This would be great to have as a config option without needing to have force unicode font on.

**Bug Fixes:**
There are a couple of bugs still plaguing TC6 including some really annoying ones like pechs trading errored potion items. Luckily a good portion of these bugs were fixed by both Thaumic Augmentation and Universal Tweaks. A fair amount of those bugs are listed [here](https://github.com/ACGaming/UniversalTweaks/discussions/341).

**Comment by xxXCuriositykilledthecatXxx** [comment]
> **Runic Shielding HUD:** While runic shielding is active in TC4, an animated overlay effect would display on your health. This was since replaced with absorption hearts as of TC5, a mod called [Thaumcraft 6 Enhanced](https://www.curseforge.com/minecraft/mc-mods/thaumcraft-6-enhanced) attempts to restore this but it is incompatible with Thaumic Augmentation and hasn't been updated for a long time.
Last I checked thaumcraft 6 enhanced works perfectly fine with augmentation. I use it personally with no issues.

**Comment by KELETU66666** [comment]
i think those things should move to a saperate mod, instead of use "TC4 Research" mod, because those things are unrelated to TC4's RESEARCH.
