### ISSUE TITLE
Inventory scanning crashes with random patches and loliasm

### ISSUE THREAD

**Issue by xxXCuriositykilledthecatXxx** [Wong-Innovations/TC4Research#42]
https://mclo.gs/ujrlvq7

**Comment by Wong-Innovations** [comment]
This is a problem with Random Patches replacing vanilla classes in an awful way. It effects many other mods. See one of many related issues: https://github.com/TheRandomLabs/RandomPatches/issues/252

Set `B:patchMinecraftClass=false` in the randompatches.cfg to fix the crash.
