### ISSUE TITLE
Implement Inventory Scanning

### ISSUE THREAD

**Issue by Wong-Innovations** [Wong-Innovations/TC4Research#9]
Implement tile entity inventory scanning and thaumometer hover scanning.

**Comment by Deiwos** [comment]
Just a note to add to this, the existing Thaumic Inventory Scanning mod is incompatible and should not be used because it provides Observations, bypassing this mod.

**Comment by Wong-Innovations** [comment]
feature introduced without the need of an addon: https://github.com/Wong-Innovations/TC4Research/commit/bbbadaab6a5ed3f0401525ad89ebcb1c14e89c14
Will be included in the next release. A config option has been provided to disabled inventory scanning (on by default).
